changelog:
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Other Changes
      labels:
        - "*"
