name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: Test
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      PACKAGE_NAME: pydtype
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pip install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

      - name: Lint with Flake8
        run: poetry run flake8 tests ${PACKAGE_NAME}

      - name: Format with Black
        run: poetry run black --check tests ${PACKAGE_NAME}

      - name: Test with pytest
        run: poetry run pytest -v tests ${PACKAGE_NAME}
